### ISSUE TITLE
Setting update rate using DMA

### ISSUE THREAD

**Issue by MasoudShah** [SMotlaq/mcp4725#1]
In the example of this project, only interrupt based communication is provided. One of the most use case of DAC modules is playing sounds and it definitely needs a specific update rate. For example a single channel music with 48khz bitrate and 16 bit depth, needs 3000 sample or update-rate per second. Using interrupt based communication is making CPU very busy and it disturbs other tasks (for example reading music data from SD-card). So a DMA-based communication is needed, but it needs that DMA send data in a specific rate as I said. How can this goal be achieved?

**Comment by SMotlaq** [comment]
Hi!
This DAC has a very low refresh rate. I couldn't get more than 1000Hz freq from the output.
It's not appropriate for audio purposes.

**Comment by MasoudShah** [comment]
Thanks for the reply
