### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by jose100310** [SMotlaq/mcp4725#2]
Mr. Smotlaq,

I try running your driver code, but it didn't work for me. It was missing an important function that deals with IRQHandler.
Here is the missing function:

void TIM1_UP_TIM10_IRQHandler(void){
	HAL_TIM_IRQHandler(&htim1);
}
How did make it work without this function?

Also, note, i was running the code to a speaker and the 100hz was really low, i increased to 300hz.

**Comment by SMotlaq** [comment]
Hi
Only the primary functions are available in the library. You can call library functions to set a value or modify MCP4725's configurations.
I created a time-variable signal in the example I wrote using a timer (TIM10) (a sine wave for example). The HAL library contains every IRQ handler. I created my project using CubeMX, so the HAL library was added to my project. If you are not using HAL, you must read the library's documentation.

In regard to frequency, I was unable to raise it above 100Hz. The signal would distort at higher frequencies. It looks that using this chip for applications involving sound is inappropriate.
